In [117]:
import numpy as np
np.set_printoptions(precision=4)

In [118]:
W_0 = np.array([[0, 0, 0],
                [0, 0, 0]], dtype=float)

In [119]:
W_1 = np.array([[0, 0, 0],], dtype=float)

In [120]:
X = np.array([[1, 1, -1],
              [-1, 1, 0],], dtype=float)

In [121]:
t = np.array([[1, 0, 1],], dtype=float)

In [122]:
f_1 = 'Sigmoid'
f_2 = 'Sigmoid'

In [123]:
lr = 1

In [124]:
def Sigmoid(x, direction='F'):
    if direction == 'F':
        return 1/(1 + np.exp(-x))
    else:
        return Sigmoid(x, 'F')*(1-Sigmoid(x, 'F'))

def Tanh(x, direction):
    if direction == 'F':
        return (1 - np.exp(-x))/(1 + np.exp(-x))
    else:
        return 0.5*(1-Tanh(x, 'F')**2) 

def ReLU(x, direction):
    if direction == 'F':
        return max(x, 0)
    else:
        return float(x > 0)

def Lin(x, direction):
    if direction == 'F':
        return x
    else:
        return 1

def activation(Z, fcn='Lin', direction = 'F'):
    A = np.array(list(map(globals()[fcn], Z, np.repeat(direction, Z.shape[0]))))
    return A

In [125]:
MAX_EPOCHS = 1

In [126]:
print('Pad bias at top of input')
A_0 = np.vstack((np.ones((1, X.shape[1])), X))
print(A_0)
for ep in range(MAX_EPOCHS):
    print('\nEPOCH-', ep+1, '='*80)
    for itr, (x, y) in enumerate(zip(A_0.T, t.T)):
        print('\nITER-', itr+1, '-'*80)
        ### Forward pass (Input -> Hidden)
        print('\n Input -> Hidden')
        Z_1 = W_0 @ x
        print(f'{Z_1 = }')
        A_1 = activation(Z_1, f_1)  
        print(f'{A_1 = }')
        ### Forward pass (Hidden -> Output)
        print('\n Hidden -> Output')
        Z_2 = W_1 @ np.vstack((np.ones((1, A_1.reshape(-1, 1).shape[1])), A_1.reshape(-1, 1)))
        print(f'{Z_2 = }')
        A_2 = activation(Z_2, f_2)  
        print(f'{A_2 = }')
        
        ### Backward pass (Output -> Hidden)
        Error = 0.5*(A_2 - y)**2
        print(f'\n{Error = }')
        
        print('\n Output -> Hidden')
        dE_dw1 = (A_2 - y) * activation(Z_2, f_2, 'B') * x
        print(f'{dE_dw1 = }')
        
        ### Backward pass  (Hidden -> Input)
        print('\n Hidden -> Input')
        dE_dw0 = (A_2 - y) * activation(Z_2, f_2, 'B') * (activation(Z_1, f_1, 'B') * x[1:]).reshape(-1, 1) @ W_1
        print(f'{dE_dw0 = }')
        
        ### Update weights
        W_1 = W_1 - lr*dE_dw1
        print(f'{W_1 = }')
        W_0 = W_0 - lr*dE_dw0
        print(f'{W_0 = }')

Pad bias at top of input
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  0.]]

EPOCH- 1 ================================================================================

ITER- 1 --------------------------------------------------------------------------------

 Input -> Hidden
Z_1 = array([0., 0.])
A_1 = array([0.5, 0.5])

 Hidden -> Output
Z_2 = array([[0.]])
A_2 = array([[0.5]])

Error = array([[0.125]])

 Output -> Hidden
dE_dw1 = array([[-0.125, -0.125,  0.125]])

 Hidden -> Input
dE_dw0 = array([[0., 0., 0.],
       [0., 0., 0.]])
W_1 = array([[ 0.125,  0.125, -0.125]])
W_0 = array([[0., 0., 0.],
       [0., 0., 0.]])

ITER- 2 --------------------------------------------------------------------------------

 Input -> Hidden
Z_1 = array([0., 0.])
A_1 = array([0.5, 0.5])

 Hidden -> Output
Z_2 = array([[0.125]])
A_2 = array([[0.5312]])

Error = array([[0.1411]])

 Output -> Hidden
dE_dw1 = array([[0.1323, 0.1323, 0.1323]])

 Hidden -> Input
dE_dw0 = array([[ 0.0041,  0.0041, -0.0041],
     