In [68]:
import numpy as np
np.set_printoptions(precision=4)

In [69]:
W_0 = np.array([[1, 1, 1, 1],], dtype=float)

In [70]:
X = np.array([[1, 1, 1],
              [2, 2, 3],
              [3, 3, 3]], dtype=float)

In [71]:
t = np.array([[1, 1, 1],], dtype=float)

In [72]:
f_1 = 'Sigmoid'

In [73]:
lr = 1

In [1]:
def Sigmoid(x, direction):
    if direction == 'F':
        return 1/(1 + np.exp(-x))
    else:
        return Sigmoid(x, 'F')*(1-Sigmoid(x, 'F'))

def Tanh(x, direction):
    if direction == 'F':
        return (1 - np.exp(-x))/(1 + np.exp(-x))
    else:
        return 0.5*(1-Tanh(x, 'F')**2) 

def ReLU(x, direction):
    if direction == 'F':
        return max(x, 0)
    else:
        return float(x > 0)

def Lin(x, direction):
    if direction == 'F':
        return x
    else:
        return 1

def activation(Z, fcn='Lin', direction = 'F'):
    A = np.array(list(map(globals()[fcn], Z, np.repeat(direction, Z.shape[0]))))
    return A

In [75]:
MAX_EPOCHS = 1

In [88]:
print('Pad bias at top of input')
A_0 = np.vstack((np.ones((1, X.shape[1])), X))
print(A_0)
for ep in range(MAX_EPOCHS):
    print('\nEPOCH-', ep+1, '='*80)
    for itr, (x, y) in enumerate(zip(A_0.T, t.T)):
        print('\nITER-', itr+1, '-'*80)
        ### Forward pass
        print('Input -> Output')
        Z_1 = W_0 @ x
        print(f'{Z_1 = }')
        A_1 = activation(Z_1, f_1)  
        print(f'{A_1 = }')
        
        ### Backward pass
        print('\nOutput -> Input')
        Error = 0.5*(A_1 - t)**2
        print(f'{Error = }')
        dE_dw = (A_1 - y) * activation(Z_1, f_1, 'B') * x
        print(f'{dE_dw = }')
        W_0 = W_0 - lr*dE_dw
        print(f'{W_0 = }')

Pad bias at top of input
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 3.]
 [3. 3. 3.]]

EPOCH- 1 ================================================================================

ITER- 1 --------------------------------------------------------------------------------
Input -> Output
Z_1 = array([7.0002])
A_1 = array([0.9991])

Output -> Input
Error = array([[4.1481e-07, 4.1481e-07, 4.1481e-07]])
dE_dw = array([-8.2886e-07, -8.2886e-07, -1.6577e-06, -2.4866e-06])
W_0 = array([[1.    , 1.    , 1.    , 1.0001]])

ITER- 2 --------------------------------------------------------------------------------
Input -> Output
Z_1 = array([7.0003])
A_1 = array([0.9991])

Output -> Input
Error = array([[4.148e-07, 4.148e-07, 4.148e-07]])
dE_dw = array([-8.2884e-07, -8.2884e-07, -1.6577e-06, -2.4865e-06])
W_0 = array([[1.    , 1.    , 1.    , 1.0001]])

ITER- 3 --------------------------------------------------------------------------------
Input -> Output
Z_1 = array([8.0003])
A_1 = array([0.9997])

Output -> Inp