In [ ]:
import numpy as np

#### AND Gate

In [ ]:
## Input Data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).T
print('Input shape:', X.shape, '\n')

## Adding Bias
A = np.vstack((np.ones((1, X.shape[1])), X))
print('A_0:\n', A,'\n')

## Weights
W = np.array([[-1, 1, 1]])
print('Weights: ', W, '\n')

## Calculate Output
Z = (W @ A).ravel()
print('Z_1: ', Z, '\n')

y_pred = [int(z > 0) for z in Z]
print('y_pred: ', y_pred, '\n')

Input shape: (2, 4) 

A_0:
 [[1. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]] 

Weights:  [[-1  1  1]] 

Z_1:  [-1.  0.  0.  1.] 

y_pred:  [0, 0, 0, 1] 



#### OR Gate

In [ ]:
## Input Data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]]).T
print('Input shape:', X.shape, '\n')

## Adding Bias
A = np.vstack((np.ones((1, X.shape[1])), X))
print('A_0:\n', A,'\n')

## Weights
W = np.array([[0, 1, 1]])
print('Weights: ', W, '\n')

## Calculate Output
Z = (W @ A).ravel()
print('Z_1: ', Z, '\n')

y_pred = [int(z > 0) for z in Z]
print('y_pred: ', y_pred, '\n')

Input shape: (2, 4) 

A_0:
 [[1. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 1. 0. 1.]] 

Weights:  [[0 1 1]] 

Z_1:  [0. 1. 1. 2.] 

y_pred:  [0, 1, 1, 1] 



#### NOT Gate

In [ ]:
## Input Data
X = np.array([[0], [1]]).T
print('Input shape:', X.shape, '\n')

## Adding Bias
A = np.vstack((np.ones((1, X.shape[1])), X))
print('A_0:\n', A,'\n')

## Weights
W = np.array([[1, -1]])
print('Weights: ', W, '\n')

## Calculate Output
Z = (W @ A).ravel()
print('Z_1: ', Z, '\n')

y_pred = [int(z > 0) for z in Z]
print('y_pred: ', y_pred, '\n')

Input shape: (1, 2) 

A_0:
 [[1. 1.]
 [0. 1.]] 

Weights:  [[ 1 -1]] 

Z_1:  [1. 0.] 

y_pred:  [1, 0] 

