In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
# Linear Activation Function
def linear(x):
    return x

# First Order Derivative of Linear Activation Function
def linear_derivative(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = linear(x)
    return tape.gradient(y, x)

# Second Order Derivative of Linear Activation Function
def linear_double_derivative(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = linear_derivative(x)
    return tape.gradient(y, x)

# Define a matrix to pass to the functions
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)

# Apply linear function to each element in the matrix
linear_result = linear(matrix)
print("Linear of the matrix:")
print(linear_result.numpy())

# Apply linear derivative to each element in the matrix
linear_derivative_result = linear_derivative(matrix)
print("\nLinear derivative of the matrix:")
print(linear_derivative_result.numpy())

# Apply linear double derivative to each element in the matrix
linear_double_derivative_result = linear_double_derivative(matrix)
print("\nLinear double derivative of the matrix:")
print(linear_double_derivative_result)


Linear of the matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Linear derivative of the matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Linear double derivative of the matrix:
None


In [ ]:
# Sigmoid Activation Function
def sigmoid(x):
    return 1 / (1 + tf.exp(-x))

# First Order Derivative of Sigmoid
def sigmoid_derivative(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = sigmoid(x)
    return tape.gradient(y, x)

# Second Order Derivative of Sigmoid
def sigmoid_double_derivative(x):
    with tf.GradientTape() as tape1:
        with tf.GradientTape() as tape2:
            tape1.watch(x)
            tape2.watch(x)
            y = sigmoid(x)
        first_derivative = tape2.gradient(y, x)
    second_derivative = tape1.gradient(first_derivative, x)
    return second_derivative

# Define a matrix to pass to the functions
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]], dtype=tf.float32)

# Apply sigmoid function to each element in the matrix
sigmoid_result = sigmoid(matrix)
print("Sigmoid of the matrix:")
print(sigmoid_result.numpy())

# Apply sigmoid derivative to each element in the matrix
sigmoid_derivative_result = sigmoid_derivative(matrix)
print("\nSigmoid derivative of the matrix:")
print(sigmoid_derivative_result.numpy())

# Apply sigmoid double derivative to each element in the matrix
sigmoid_double_derivative_result = sigmoid_double_derivative(matrix)
print("\nSigmoid double derivative of the matrix:")
print(sigmoid_double_derivative_result.numpy())


Sigmoid of the matrix:
[[0.7310586  0.880797   0.95257413]
 [0.98201376 0.9933072  0.9975274 ]
 [0.999089   0.99966466 0.9998766 ]]

Sigmoid derivative of the matrix:
[[1.96611941e-01 1.04993574e-01 4.51766625e-02]
 [1.76627059e-02 6.64805667e-03 2.46650958e-03]
 [9.10221308e-04 3.35237681e-04 1.23379359e-04]]

Sigmoid double derivative of the matrix:
[[-0.09085775 -0.07996249 -0.04089158]
 [-0.01702734 -0.00655907 -0.00245431]
 [-0.00090856 -0.00033501 -0.00012335]]


In [ ]:
# ReLU Activation Function
def relu(x):
    return tf.maximum(0, x)

# First Order Derivative of ReLU Activation Function
def relu_derivative(x):
    return tf.cast(x > 0, dtype=tf.float32)

# Second Order Derivative of ReLU Activation Function
def relu_double_derivative(x):
    return tf.zeros_like(x, dtype=tf.float32)

# Define a matrix to pass to the functions
matrix = tf.constant([[1, 2, 3],
                      [-4, 5, -6],
                      [7, -8, 9]], dtype=tf.float32)

# Apply ReLU function to each element in the matrix
relu_result = relu(matrix)
print("ReLU of the matrix:")
print(relu_result.numpy())

# Apply ReLU derivative to each element in the matrix
relu_derivative_result = relu_derivative(matrix)
print("\nReLU derivative of the matrix:")
print(relu_derivative_result.numpy())

# Apply ReLU double derivative to each element in the matrix
relu_double_derivative_result = relu_double_derivative(matrix)
print("\nReLU double derivative of the matrix:")
print(relu_double_derivative_result.numpy())


ReLU of the matrix:
[[1. 2. 3.]
 [0. 5. 0.]
 [7. 0. 9.]]

ReLU derivative of the matrix:
[[1. 1. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]

ReLU double derivative of the matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Tanh Activation Function
def tanh(x):
    return tf.math.tanh(x)

# First Order Derivative of Tanh Activation Function
def tanh_derivative(x):
    with tf.GradientTape() as tape:
        tape.watch(x)
        y = tanh(x)
    return tape.gradient(y, x)

# Second Order Derivative of Tanh Activation Function
def tanh_double_derivative(x):
    with tf.GradientTape() as tape1:
        with tf.GradientTape() as tape2:
            tape1.watch(x)
            tape2.watch(x)
            y = tanh_derivative(x)
        first_derivative = tape2.gradient(y, x)
    second_derivative = tape1.gradient(first_derivative, x)
    return second_derivative

# Define a matrix to pass to the functions
matrix = tf.constant([[1, 2, 3],
                      [-4, 5, -6],
                      [7, -8, 9]], dtype=tf.float32)

# Apply tanh function to each element in the matrix
tanh_result = tanh(matrix)
print("Tanh of the matrix:")
print(tanh_result.numpy())

# Apply tanh derivative to each element in the matrix
tanh_derivative_result = tanh_derivative(matrix)
print("\nTanh derivative of the matrix:")
print(tanh_derivative_result.numpy())

# Apply tanh double derivative to each element in the matrix
tanh_double_derivative_result = tanh_double_derivative(matrix)
print("\nTanh double derivative of the matrix:")
print(tanh_double_derivative_result.numpy())


Tanh of the matrix:
[[ 0.7615942   0.9640276   0.9950547 ]
 [-0.9993292   0.99990916 -0.99998784]
 [ 0.99999833 -1.          1.        ]]

Tanh derivative of the matrix:
[[4.1997433e-01 7.0650816e-02 9.8661184e-03]
 [1.3411045e-03 1.8167496e-04 2.4318695e-05]
 [3.3378601e-06 0.0000000e+00 0.0000000e+00]]

Tanh double derivative of the matrix:
[[6.2162668e-01 2.5265405e-01 3.8880430e-02]
 [5.3536268e-03 7.2650181e-04 9.7271230e-05]
 [1.3351373e-05 0.0000000e+00 0.0000000e+00]]
