**Experiment 6**

In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [ ]:
X = np.array([[1, 1, -1],
              [-1, 1, 0],], dtype=float)

t = np.array([[1, 0, 1],], dtype=float)

W_0 = np.array([[0, 0, 0],
                [0, 0, 0]], dtype=float)

W_1 = np.array([[0, 0, 0],], dtype=float)

f_1 = 'Sigmoid'
f_2 = 'Sigmoid'

In [ ]:
lr = 1
MAX_EPOCHS = 1

In [ ]:
def Sigmoid(x, direction='F'):
    if direction == 'F':
        return 1/(1 + np.exp(-x))
    else:
        return Sigmoid(x, 'F')*(1-Sigmoid(x, 'F'))

In [ ]:
print('Pad bias at top of input')
A_0 = np.vstack((np.ones((1, X.shape[1])), X))
print(A_0)
for ep in range(MAX_EPOCHS):
    print('\nEPOCH-', ep+1, '='*80)
    for itr, (x, y) in enumerate(zip(A_0.T, t.T)):
      print(itr, (x,y))
        print('\nITER-', itr+1, '-'*80)
        ### Forward pass (Input -> Hidden)
        print('\n Input -> Hidden')
        Z_1 = W_0 @ x
        print(f'{Z_1 = }')
        A_1 = Sigmoid(Z_1)
        print(f'{A_1 = }')
        ### Forward pass (Hidden -> Output)
        print('\n Hidden -> Output')
        print(A_1)
        Z_2 = W_1 @ np.vstack((np.ones((1, A_1.reshape(-1, 1).shape[1])), A_1.reshape(-1, 1)))
        print(f'{Z_2 = }')
        A_2 = Sigmoid(Z_2)
        print(f'{A_2 = }')

        ### Backward pass (Output -> Hidden)
        Error = 0.5*(A_2 - y)**2
        print(f'\n{Error = }')

        print('\n Output -> Hidden')
        dE_dw1 = (A_2 - y) * Sigmoid(Z_2, 'B') * x
        print(f'{dE_dw1 = }')

        ### Backward pass  (Hidden -> Input)
        print('\n Hidden -> Input')
        dE_dw0 = (A_2 - y) * Sigmoid(Z_2, 'B') * (Sigmoid(Z_1, 'B') * x[1:]).reshape(-1, 1) @ W_1
        print(f'{dE_dw0 = }')

        ### Update weights
        W_1 = W_1 - lr*dE_dw1
        print(f'{W_1 = }')
        W_0 = W_0 - lr*dE_dw0
        print(f'{W_0 = }')

Pad bias at top of input
[[ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  0.]]

EPOCH- 1 ================================================================================
0 (array([ 1.,  1., -1.]), array([1.]))

ITER- 1 --------------------------------------------------------------------------------

 Input -> Hidden
Z_1 = array([0., 0.])
A_1 = array([0.5, 0.5])

 Hidden -> Output
[0.5 0.5]
1
Z_2 = array([[0.]])
A_2 = array([[0.5]])

Error = array([[0.125]])

 Output -> Hidden
dE_dw1 = array([[-0.125, -0.125,  0.125]])

 Hidden -> Input
dE_dw0 = array([[0., 0., 0.],
       [0., 0., 0.]])
W_1 = array([[ 0.125,  0.125, -0.125]])
W_0 = array([[0., 0., 0.],
       [0., 0., 0.]])
1 (array([1., 1., 1.]), array([0.]))

ITER- 2 --------------------------------------------------------------------------------

 Input -> Hidden
Z_1 = array([0., 0.])
A_1 = array([0.5, 0.5])

 Hidden -> Output
[0.5 0.5]
1
Z_2 = array([[0.125]])
A_2 = array([[0.53120937]])

Error = array([[0.1410917]])

 Output -> Hidden
dE_